In [5]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

In [6]:
xy = np.loadtxt('data-03-diabetes.csv', delimiter=',',dtype=np.float32)
type(xy)
print(xy.shape)

# 학습 데이터 70%, 531개
# 검증 데이터 30%, 228개

(759, 9)


In [7]:
x_train = xy[:531,:-1]
y_train = xy[:531,[-1]]
print(x_train.shape, y_train.shape)
x_test = xy[531:,:-1]
y_test = xy[531:,[-1]]
print(x_test.shape, y_test.shape)

(531, 8) (531, 1)
(228, 8) (228, 1)


In [8]:
W = tf.Variable(tf.random.normal([8,1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')

In [9]:
# X * W + b = Y
# 예측함수, H(x) = Sigmoid(X * W +b)
# tf.sigmoid() : tf.div(1.,1.+tf.exp(-tf.matmul(X,W) +b)

In [10]:
def hypo(X):
    return tf.sigmoid(tf.matmul(X,W) +b) # 0과 1사이의 값이 출력

In [11]:
# 비용 함수 : logloss, 2진 분류 모델 / 평균오차를 구해야 함으로 reduce_mean을 사용
def cost_func():
    cost = -tf.reduce_mean(y_train*tf.math.log(hypo(x_train)) +
                         (1-y_train)*tf.math.log(1-hypo(x_train)))
    return cost

In [12]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

In [16]:
# 학습 시작
print('***** Start Learning!!')
for step in range(10000):
    with tf.GradientTape() as tape:
        cost = cost_func()
    gradients = tape.gradient(cost, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    
    if step % 100 == 0:
        print('%04d' % step, '손실 값: [', cost.numpy(), ']',
              ' W:', W.numpy(), ' b:', b.numpy())
print('***** Learning Finished!!')

***** Start Learning!!
0000 손실 값: [ 0.81213015 ]  W: [[-0.19030644]
 [-0.9402895 ]
 [-0.02964124]
 [-0.7525403 ]
 [ 1.3131526 ]
 [-0.6285471 ]
 [ 0.8440665 ]
 [-0.09899934]]  b: [0.23652852]
0100 손실 값: [ 0.5277143 ]  W: [[-0.6510297 ]
 [-1.9078268 ]
 [ 0.23280826]
 [-1.2235696 ]
 [ 0.70609117]
 [-1.4086562 ]
 [ 0.3165267 ]
 [-0.42911762]]  b: [0.64593804]
0200 손실 값: [ 0.50210696 ]  W: [[-0.700372  ]
 [-2.6286895 ]
 [ 0.16853541]
 [-1.2493114 ]
 [ 0.43074816]
 [-1.8856583 ]
 [ 0.0790083 ]
 [-0.26116478]]  b: [0.66892827]
0300 손실 값: [ 0.49339905 ]  W: [[-0.7115045 ]
 [-3.0237334 ]
 [ 0.19624364]
 [-1.1704351 ]
 [ 0.2555695 ]
 [-2.166043  ]
 [-0.1320182 ]
 [-0.10620078]]  b: [0.6788835]
0400 손실 값: [ 0.4899784 ]  W: [[-7.1795529e-01]
 [-3.2340927e+00]
 [ 2.1906522e-01]
 [-1.0466375e+00]
 [ 1.3929123e-01]
 [-2.3197508e+00]
 [-3.0422193e-01]
 [ 1.3162857e-03]]  b: [0.6713181]
0500 손실 값: [ 0.4884259 ]  W: [[-0.7261078 ]
 [-3.3358548 ]
 [ 0.22019202]
 [-0.9183983 ]
 [ 0.05383505]
 [-2.4010112 

In [13]:
print("weight = ", W.numpy)
print("bias = ", b.numpy)

weight =  <bound method BaseResourceVariable.numpy of <tf.Variable 'weight:0' shape=(8, 1) dtype=float32, numpy=
array([[-0.18030666],
       [-0.95028627],
       [-0.03964049],
       [-0.7425406 ],
       [ 1.3231523 ],
       [-0.61854804],
       [ 0.8540664 ],
       [-0.08899953]], dtype=float32)>>
bias =  <bound method BaseResourceVariable.numpy of <tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.22652863], dtype=float32)>>


In [19]:
tf.cast(hypo(x_test).numpy() > 0.5, dtype=tf.float32)

<tf.Tensor: shape=(228, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
 

In [25]:
tf.reduce_mean(tf.cast(tf.equal(y_test,preds),dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=0.78070176>

In [18]:
# 정확도 측정 : accuracy computation
def predict(X):
    return tf.cast(hypo(X) > 0.5,dtype=tf.float32)

# 검증 데이터를 사용하여 예측 (70%:30%)
preds = predict(x_test)
accuracy = tf.reduce_mean(tf.cast(tf.equal(preds,y_test),dtype=tf.float32))

print('Accuracy:',accuracy.numpy()) # Accuracy: 0.78070176
# print('Hypothesis:\n',hypothesis(x_test).numpy())
# print('Predict:\n',preds.numpy())

Accuracy: 0.78070176
