In [1]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

In [2]:
train_data = np.loadtxt("boston_train.csv",delimiter=',',skiprows=1,dtype=np.float32)
test_data = np.loadtxt("boston_test.csv",delimiter=',',skiprows=1,dtype=np.float32)
print(train_data.shape)
print(test_data.shape)

(400, 10)
(100, 10)


In [3]:
x_train = train_data[:,:-1]
y_train = train_data[:,[-1]]
x_test = test_data[:,:-1]
y_test = test_data[:,[-1]]
print(x_train.shape, y_train.shape)
print(x_train.shape, y_train.shape)

(400, 9) (400, 1)
(400, 9) (400, 1)


In [4]:
# layer 1
# 400 9 * 9 5 = 400 5
W1 = tf.Variable(tf.random.normal([9,5]), name="weight1")
b1 = tf.Variable(tf.random.normal([5]), name="bias1")

def layer1(X):
    return tf.nn.relu(tf.matmul(X, W1)+b1)

In [5]:
# layer 2
# 400 5 * 5 2 = 400 2
W2 = tf.Variable(tf.random.normal([5,2]), name="weight2")
b2 = tf.Variable(tf.random.normal([2]), name="bias2")

def layer2(X):
    return tf.nn.relu(tf.matmul(layer1(X), W2)+b2)

In [6]:
# Layer 3 (출력층, Output Layer)
# 400 2 * 2 1 = 400 1

W3 = tf.Variable(tf.random.normal([2,1]), name="weight3")
b3 = tf.Variable(tf.random.normal([1]), name="bias3")

In [7]:
def hypothesis(X):
    return tf.matmul(layer2(X),W3)+b3

In [8]:
# 비용함수 : (Hx - y)^2 의 평균
def cost_func():
    cost = tf.reduce_mean(tf.square((hypothesis(x_train) - y_train)))
    return cost

In [9]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

In [10]:
# 학습 시작
print('***** Start Learning!!')
for step in range(15001):
    optimizer.minimize(cost_func,var_list=[W1,b1,W2,b2,W3,b3])
    if step % 1000 == 0:
        print('%04d'%step,'cost:[',cost_func().numpy(),']',
             ' W1:',W1.numpy(),' b1:',b1.numpy())  
        
print('***** Learning Finished!!')

***** Start Learning!!
0000 cost:[ 642.0701 ]  W1: [[-0.18030666 -0.9602862  -0.03964049 -0.7325411   1.3231523 ]
 [-0.61854804  0.8440664  -0.08899953  2.4588697   0.762508  ]
 [ 1.2659615   0.9701489   1.5293121  -0.56500345  0.8987044 ]
 [-1.250801   -0.8704956   1.260746   -0.67304987  0.02615766]
 [ 0.22328745  0.94914025 -0.37048063  0.04484768  0.13794525]
 [ 0.7596925   0.4540491  -1.3800851  -0.46065533  1.1383884 ]
 [-0.91330576  0.73427117 -0.67893195 -0.8256956  -0.49823263]
 [-0.9336107  -0.01845589 -0.04050136  2.0287025  -1.4186655 ]
 [-0.90990627  1.1592344  -0.1118804   0.3348444  -1.4201527 ]]  b1: [0.22652863 0.8006553  0.7466094  0.7849702  0.72448725]
1000 cost:[ 48.0005 ]  W1: [[-0.18030666 -1.1792763  -0.03964049 -3.7614791   1.3231523 ]
 [-0.61854804  0.41731283 -0.08899953  0.21305664  0.762508  ]
 [ 1.2659615   0.63132334  1.5293121  -1.3043573   0.8987044 ]
 [-1.250801   -1.274703    1.260746    4.377831    0.02615766]
 [ 0.22328745  0.5254018  -0.37048063  8

In [11]:
preds = hypothesis(x_test).numpy()

In [12]:
# 정확도 측정(RMSE)
def get_rmse(y_test,preds):
    squared_error = 0
    for k,_ in enumerate(y_test):
        squared_error += (preds[k] - y_test[k])**2
    mse = squared_error/len(y_test)    
    rmse = np.sqrt(mse)
    return rmse[0]  

print('RMSE:', get_rmse(y_test,preds))

RMSE: 3.618093
