In [2]:
import tensorflow as tf
import numpy as np
#상수 : tf.constant()
s = tf.constant("Hello Tensorflow!!")
print(s)

tf.Tensor(b'Hello Tensorflow!!', shape=(), dtype=string)


In [6]:
# 변수 : tf.Variable()
# 초기 값이 미리 설정,주로 텐서플로 내부에서 연산시 변경되는 변수에 사용,weight과 bias

In [3]:
a = tf.constant([[1,2],
                [3,4]])
b = tf.constant([[1,1],
                [0,1]])
c = tf.matmul(a,b) #행렬 곱셉  공식: (m, n)(n, l)= (m, l)
print(c)

tf.Tensor(
[[1 3]
 [3 7]], shape=(2, 2), dtype=int32)


In [4]:
tf.__version__

'2.16.1'

In [5]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 8099318164326562506
 xla_global_id: -1]

In [7]:
### tf.Tensor: 텐서 객체
#### 텐서는 다차원 배열로 넘파이(NumPy) ndarray 객체와 비슷하며,
#### tf.Tensor 객체는 데이터 타입과 크기를 가지고 있다.
#### 또한 tf.Tensor는 GPU 같은 가속기 메모리에 상주할 수 있다.
#### 텐서플로는 텐서를 생성하고 이용하는 풍부한 연산 라이브러리(tf.add, tf.matmul, tf.linalg.inv 등.)를 제공하며
#### 연산수행 시 자동으로 텐서를 파이썬 네이티브(native) 타입으로 변환하여 연산한다

In [10]:
#tf.Variable
a = tf.Variable(1)
b = tf.Variable(2)
c = tf.add(a,b)
print(c)

tf.Tensor(3, shape=(), dtype=int32)


In [12]:
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
# 10 : scalar, 0차원
# [1 2 3] : vector, 1차원, Rank 1 
# [[1. 2.]   : matrix(행렬), 2차원, Rank 2
    [3. 4.]]
#[[[1. 2.]    : 3d-Tensor, 3차원, Rank 3
    [3. 4.]
    [[1. 2.]
     [3. 4.]]]

In [20]:
# 텐서 객체
a = tf.constant([[1.,2.],
                 [3.,4.]])
print(a)
print(type(a))
print(a.shape)
print(a.dtype)
# 넘파이 객체로 변환
n = a.numpy()
print(n)
print(type(n))
# 파이썬 네이티브로 변환
a = tf.constant(10)
b = int(a)
print(b)
print(type(b))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]]
<class 'numpy.ndarray'>
10
<class 'int'>
