# Scores_linear_regression[다항회귀]

In [2]:
import tensorflow as tf
import numpy as np

In [53]:
xy = np.loadtxt('data-02-test-score.csv', delimiter=',',skiprows=1,
                dtype=np.float32)
xy.shape

(25, 4)

In [46]:
x_train = xy[:,:-1]
y_train = xy[:,[-1]]
print(x_train.shape, y_train.shape)

(25, 3) (25, 1)


In [47]:
xy

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [48]:
# X * W = Y
# (m,n) * (n,l) = (m,l)
#(25,3) * (3,1) = (25,1)
W = tf.Variable(tf.random.normal([3,1]),name='weight')
b = tf.Variable(tf.random.normal([1]),name='bias')
print(W)
print(b)

<tf.Variable 'weight:0' shape=(3, 1) dtype=float32, numpy=
array([[ 1.8309999],
       [-0.6803925],
       [ 1.5691224]], dtype=float32)>
<tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([-0.4565232], dtype=float32)>


In [49]:
# 예측함수 : H(X1, X2, X3) = W1*X1+ W2*X2+ W3*X3 + b
def hypo(X):
    return tf.matmul(X,W) + b # 내적 곱셈

In [50]:
# 비용 함수 : (Hx - y)^2의 평균
# tf.square()
def cost_func():
    cost = tf.reduce_mean(tf.square(hypo(x_train) - y_train))
    return cost

In [51]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

In [52]:
# 학습 시작
print('***** Start Learning!!')
for step in range(10000):
    with tf.GradientTape() as tape:
        cost = cost_func()
    gradients = tape.gradient(cost, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))
    
    if step % 100 == 0:
        print('%04d' % step, '손실 값: [', cost.numpy(), ']',
              ' W:', W.numpy(), ' b:', b.numpy())
print('***** Learning Finished!!')

***** Start Learning!!
0000 손실 값: [ 3252.5996 ]  W: [[ 1.8209999]
 [-0.6903925]
 [ 1.5591224]]  b: [-0.4665232]
0100 손실 값: [ 62.78507 ]  W: [[ 1.5910391]
 [-0.9017552]
 [ 1.3315247]]  b: [-0.69305634]
0200 손실 값: [ 60.931065 ]  W: [[ 1.5778211]
 [-0.8769438]
 [ 1.3232589]]  b: [-0.6992226]
0300 손실 값: [ 58.64176 ]  W: [[ 1.5591849]
 [-0.8460596]
 [ 1.3113229]]  b: [-0.7085887]
0400 손실 값: [ 55.996567 ]  W: [[ 1.5369164 ]
 [-0.80952007]
 [ 1.2973912 ]]  b: [-0.7197206]
0500 손실 값: [ 53.094547 ]  W: [[ 1.5114974 ]
 [-0.76827013]
 [ 1.281936  ]]  b: [-0.7323472]
0600 손실 값: [ 50.016354 ]  W: [[ 1.4832802]
 [-0.7230556]
 [ 1.2653419]]  b: [-0.74627167]
0700 손실 값: [ 46.831085 ]  W: [[ 1.4525554]
 [-0.6745159]
 [ 1.2479491]]  b: [-0.7613359]
0800 손실 값: [ 43.599033 ]  W: [[ 1.4195774]
 [-0.6232267]
 [ 1.2300714]]  b: [-0.7774063]
0900 손실 값: [ 40.373287 ]  W: [[ 1.3845841 ]
 [-0.56972516]
 [ 1.2120013 ]]  b: [-0.79436845]
1000 손실 값: [ 37.19975 ]  W: [[ 1.3478024]
 [-0.5145182]
 [ 1.1940118]]  b: [-

In [56]:
print("weight = ", W.numpy)
print("bias = ", b.numpy)
#H(x1,x2,x3) = 0.35595858*X1 + 0.54253817*X2 + 1.1674615*X3 - 4.3357735

weight =  <bound method BaseResourceVariable.numpy of <tf.Variable 'weight:0' shape=(3, 1) dtype=float32, numpy=
array([[0.35595858],
       [0.54253817],
       [1.1674615 ]], dtype=float32)>>
bias =  <bound method BaseResourceVariable.numpy of <tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([-4.3357735], dtype=float32)>>


In [61]:
# 예측
test = [[ 73.,  80.,  75.],
       [ 93.,  88.,  93.],
       [ 89.,  91.,  90.],
       [ 96.,  98., 100.],
       [ 73.,  66.,  70.]]
test_1 = np.array(test,dtype=np.float32)
pred = hypo(test_1)
print(pred)

tf.Tensor(
[[152.61188]
 [185.08565]
 [181.78705]
 [199.75114]
 [139.17903]], shape=(5, 1), dtype=float32)


In [68]:
# 정확도 측정 : RMSE
def get_rmse(y_test,preds):
    squared_error = 0
    for k,_ in enumerate(y_test):
        squared_error += (preds[k] - y_test[k])**2
    mse = squared_error/len(y_test)  
    rmse = np.sqrt(mse)
    return rmse[0]

x_test = x_train
y_test = y_train

preds = hypo(x_test).numpy()
print('Rmse:',get_rmse(y_test,preds))

Rmse: 2.3953776
